# Generated by Django 2.2.24 on 2022-01-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20220107_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
    ]
