# Generated by Django 2.2.24 on 2022-01-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='isComplete',
        ),
    ]
