# Generated by Django 2.2.24 on 2022-01-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20220112_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isComplete',
            new_name='isCompleted',
        ),
    ]
