# Generated by Django 2.2.24 on 2022-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20220112_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
